'use client'
import Sidebar from "@/components/Sidebar";
import "../styles/globals.css";

import { Bad_Script } from "next/font/google"
import { AnimatePresence } from "framer-motion";
import { AppProps } from "next/app";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const font = Bad_Script(
  {
    weight:["400"],
    subsets: ["latin"]
  }
)

export default function RootLayout({ children }: {children: React.ReactNode}) {
  // const url = router.route
  return (
    <html lang="en">
      <body className={`bg-black ${font.className}`}>
        <main className="lg:grid gap-0 grid-cols-6 grid-rows-1">
          <Sidebar />
          <AnimatePresence
                mode="wait"
                initial={false}
                onExitComplete={() => window.scrollTo(0, 0)}
            >
                {/* <Component {...pageProps} canonical={url} key={url} /> */}
                {children}
          </AnimatePresence>
          {/* {children} */}
        </main>
        </body>
    </html>
  )
}
