import Sidebar from "@/components/Sidebar";
import "../styles/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Bad+Script&display=swap" rel="stylesheet" />
      </head>
      <body>
        <main className="lg:grid gap-0 grid-cols-6 grid-rows-1">
          <Sidebar />
          {children}
        </main>
        </body>
    </html>
  )
}
